apiVersion: apps/v1
kind: Deployment
metadata:
  name: token-validator
  namespace: {{ $.Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: token-validator
  template:
    metadata:
      labels:
        app: token-validator
    spec:
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: token-validator-db-pvc
      initContainers:
        - name: db-migrate
          image: {{.Values.image.repository }}:{{.Values.image.tag }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          command: [ "flask", "db", "upgrade" ]
          env:
            - name: DATABASE_URI
              value: "sqlite:////db/token_validator.db"
          volumeMounts:
            - name: db-storage
              mountPath: /db
      containers:
        - name: token-validator
          image: {{.Values.image.repository }}:{{.Values.image.tag }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: db-storage
              mountPath: /db
          env:
            - name: DATABASE_URI
              value: "sqlite:////db/token_validator.db"
            - name: OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.oidc.secrets.existingSecret.name }}
                  key: {{ .Values.oidc.secrets.existingSecret.clientIdKey }}
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.oidc.secrets.existingSecret.name }}
                  key: {{ .Values.oidc.secrets.existingSecret.clientSecretKey }}
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretKey.existingSecret.name }}
                  key: {{ .Values.secretKey.existingSecret.key }}
            - name: ADMIN_GROUP
              value: {{ .Values.oidc.adminGroup }}
            - name: OIDC_AUTHORIZE_URL
              value: {{ .Values.oidc.authorizeURL }}
            - name: OIDC_CONFIGURATION_URL
              value: {{ .Values.oidc.configurationURL }}
            - name: OIDC_TOKEN_URL
              value: {{ .Values.oidc.tokenURL }}
            - name: OIDC_USERINFO_URL
              value: {{ .Values.oidc.userinfoURL }}
            - name: PREFERRED_URL_SCHEME
              value: 'https'
  strategy:
    type: Recreate
