apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: token-validator-db-pvc
  namespace: {{ $.Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
