apiVersion: v1
kind: Service
metadata:
  name: token-validator
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    app: token-validator
  ports:
  - name: http
    port: 80
    targetPort: 5000
  type: ClusterIP
