{{ if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.key }}
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: datalab-vault
    kind: ClusterSecretStore
  target:
    name: {{ .Values.oidc.secrets.existingSecret.name }}
  data:
    - secretKey: {{ .Values.oidc.secrets.existingSecret.clientIdKey }}
      remoteRef:
        key: {{ .Values.externalSecret.key }}
        property: OIDC_CLIENT_ID

    - secretKey: {{ .Values.oidc.secrets.existingSecret.clientSecretKey }}
      remoteRef:
        key: {{ .Values.externalSecret.key }}
        property: OIDC_CLIENT_SECRET

    - secretKey: {{ .Values.secretKey.existingSecret.key }}
      remoteRef:
        key: {{ .Values.externalSecret.key }}
        property: SECRET_KEY
  {{ end }}