image:
  repository: ghcr.io/tu-wien-datalab/token-validator
  tag: main
  imagePullPolicy: Always

externalSecret:
  enabled: true
  key: token-validator-secrets

oidc:
  adminGroup: "ds-ray-cluster"
  authorizeURL: https://login.datalab.tuwien.ac.at/application/o/authorize/
  configurationURL: https://login.datalab.tuwien.ac.at/application/o/tgi/.well-known/openid-configuration
  tokenURL: https://login.datalab.tuwien.ac.at/application/o/token/
  userinfoURL: https://login.datalab.tuwien.ac.at/application/o/userinfo/
  secrets:
    existingSecret:
      name: token-validator-secrets
      clientIdKey: OIDC_CLIENT_ID
      clientSecretKey: OIDC_CLIENT_SECRET


secretKey:
  existingSecret:
    name: token-validator-secrets
    key: SECRET_KEY


ingress:
  enabled: true
  className: nginx
  annotations:
    # tls
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: datalab-issuer
  hosts:
    - host: tgi.mlops-staging.datalab.tuwien.ac.at
      paths:
        - path: "/"
          pathType: "Prefix"
  tls:
    - secretName: token-validator-tls
      hosts:
        - tgi.mlops-staging.datalab.tuwien.ac.at
